#!/bin/bash

# Confirm the database exists, if not create it
if ! /usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" -p"$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -P "$OPENSHIFT_MYSQL_DB_PORT" -e "select * from users;" "$OPENSHIFT_APP_NAME"> /dev/null 2>&1
then
	echo
	echo "Database schema not yet added, adding now"
	/usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" -p"$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -P "$OPENSHIFT_MYSQL_DB_PORT" -e "create database $OPENSHIFT_APP_NAME character set utf8 collate utf8_bin;"
	echo "Adding schema.sql"
	/usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" -p"$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -P "$OPENSHIFT_MYSQL_DB_PORT" "$OPENSHIFT_APP_NAME" < ${OPENSHIFT_DATA_DIR}zabbix-2.2.1/database/mysql/schema.sql
	echo "Adding images.sql"
	/usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" -p"$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -P "$OPENSHIFT_MYSQL_DB_PORT" "$OPENSHIFT_APP_NAME" < ${OPENSHIFT_DATA_DIR}zabbix-2.2.1/database/mysql/images.sql
	echo "Adding data.sql"
	/usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" -p"$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -P "$OPENSHIFT_MYSQL_DB_PORT" "$OPENSHIFT_APP_NAME" < ${OPENSHIFT_DATA_DIR}zabbix-2.2.1/database/mysql/data.sql
else
	echo "Database already configured"
fi

# Configure the Zabbix Server and Agent
echo "Configuring Zabbix Server"
eval echo "\"$(cat <<EOF_$RANDOM
$(<${OPENSHIFT_REPO_DIR}conf/zabbix_server.conf)
EOF_$RANDOM
)\"" >> ${OPENSHIFT_REPO_DIR}zabbix/etc/zabbix_server.conf

echo "Configuring Zabbix Agent"
eval echo "\"$(cat <<EOF_$RANDOM
$(<${OPENSHIFT_REPO_DIR}conf/zabbix_agentd.conf)
EOF_$RANDOM
)\"" >> ${OPENSHIFT_REPO_DIR}zabbix/etc/zabbix_agentd.conf

# Restart Zabbix Server and Agent
echo "Restarting Zabbix Server"
killall -9 zabbix_server
sleep 5
${OPENSHIFT_REPO_DIR}zabbix/sbin/zabbix_server
echo "Restarting Zabbix Agent"
killall -9 zabbix_agentd
sleep 5
${OPENSHIFT_REPO_DIR}zabbix/sbin/zabbix_agentd
