#!/bin/bash

# Download the latest Zabbix release
echo "Download and install the latest stable version of Zabbix"
echo

mkdir -p ${OPENSHIFT_DATA_DIR}downloads
rm -rf ${OPENSHIFT_DATA_DIR}downloads/*
wget -P ${OPENSHIFT_DATA_DIR}downloads http://sourceforge.net/projects/zabbix/files/ZABBIX%20Latest%20Stable/2.2.1/zabbix-2.2.1.tar.gz/download
tar -xzf ${OPENSHIFT_DATA_DIR}downloads/zabbix-2.2.1.tar.gz -C ${OPENSHIFT_DATA_DIR}/


# Confirm the database exists, if not create it
if ! /usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password "$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -P "$OPENSHIFT_MYSQL_DB_PORT" -e "select * from users;" "$OPENSHIFT_APP_NAME" > /dev/null 2>&1
then
	echo
	echo "Database schema not found, adding it now."
	echo "CREATING DB"
	/usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" -p "$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -P "$OPENSHIFT_MYSQL_DB_PORT" -e "create database $OPENSHIFT_APP_NAME character set utf8 collate utf8_bin;"
	echo "ADDING SCHEMA1"
	/usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" -p "$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -P "$OPENSHIFT_MYSQL_DB_PORT" "OPENSHIFT_APP_NAME" <  ${OPENSHIFT_DATA_DIR}zabbix-2.2.1/database/mysql/schema.sql
	echo "ADDING SCHEMA2"
	/usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" -p "$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -P "$OPENSHIFT_MYSQL_DB_PORT" "OPENSHIFT_APP_NAME" <  ${OPENSHIFT_DATA_DIR}zabbix-2.2.1/database/mysql/images.sql
	echo "ADDING SCHEMA3"
	/usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" -p "$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -P "$OPENSHIFT_MYSQL_DB_PORT" "OPENSHIFT_APP_NAME" <  ${OPENSHIFT_DATA_DIR}zabbix-2.2.1/database/mysql/data.sql
else
	echo "Database already configured."
fi
	
